name: Build

on:
  push:
    branches: [ master ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: openjfx/samples
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 16
      - name: Test
        run: |
          export DISPLAY=:90
          mkdir /home/runner/.vnc
          echo 123456 | vncpasswd -f > /home/runner/.vnc/passwd
          chmod -v 600 /home/runner/.vnc/passwd
          vncserver :90 -localhost -nolisten tcp
          mvn clean compile -f CommandLine/Modular/Maven/hellofx
          mvn javafx:run -f CommandLine/Modular/Maven/hellofx
          vncserver -kill :90
          